# Generated by Django 5.2.13 on 2026-04-10 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Только латиница и цифры', regex='^[a-zA-Z0-9]+$')])),
                ('email', models.EmailField(max_length=254)),
                ('home_page', models.URLField(blank=True, null=True)),
                ('text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
            ],
        ),
    ]
